### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [AASOxRevolution/prj-rev-bwfs-tea-cozy#2]
Alternatively, you could combine these lines into:

```css
h2, h5 {
  font-weight: bold;
  display: block;
}
```

https://github.com/AASOxRevolution/prj-rev-bwfs-tea-cozy/blob/master/tea%20cozy/css/style.css#L39-L46
