### ISSUE TITLE
body margin

### ISSUE THREAD

**Issue by cyouh95** [AASOxRevolution/prj-rev-bwfs-tea-cozy#4]
Additionally, you could specify a `margin-top` of `0px` for the `body` element to get rid of the extra space between the menu bar and the top of the page.

```css
body {
  margin-top: 0px;
  ...
}
```

https://github.com/AASOxRevolution/prj-rev-bwfs-tea-cozy/blob/master/tea%20cozy/css/style.css#L2
